import { SetToken }                   from './AuthHelpers'
import { OpenAppointmentsModal }      from './ModalHelpers'
import { ShowProgress, HideProgress } from './LoaderHelpers'
import { SundayDate, 
         IsToday,
         IsSelected,
         IsAvailable,
         AvailableDay,
         AddDaysToDate, 
         LastDayOfMonth, 
         FirstDayOfMonth, 
         GetCalendarDays, 
         GetCalendarWeeks, 
         CreateDateString, 
         StartBookingTimer,
         timeFromDisplayTime,
         timeFromMilitaryTime,
         ampmFromDisplayTime,
         GetFirstCalendarDate }       from './DateHelpers'
import { ParseInt,
         ParseDate,
         FormatTime,
         FormatDuration,
         ParsePhoneNumber,
         FormatPhoneNumber,
         FormatServiceDescription }   from './FormatHelpers'
import { IsEmpty,
         IsNotEmpty,
         GetFunctionName,
         GetUrlParameter,
         CreateAvailabilityUrl,
         AddUrlParam,
         DataValue,
         CheckboxChecked,
         GetFormElementDataValue }    from './IdentifierHelpers'


export const OnSchedHelpers = {
  SundayDate,
  IsToday,
  IsAvailable,
  IsSelected,
  AvailableDay,
  IsEmpty,
  IsNotEmpty,
  GetFunctionName,
  GetUrlParameter,
  CreateAvailabilityUrl,
  AddUrlParam,
  GetFormElementDataValue,
  CreateDateString,
  GetFirstCalendarDate,
  GetCalendarDays,
  GetCalendarWeeks,
  FirstDayOfMonth,
  LastDayOfMonth,
  AddDaysToDate,
  ShowProgress,
  HideProgress,
  ParseDate,
  ParseInt,
  FormatServiceDescription,
  FormatTime,
  FormatDuration,
  FormatPhoneNumber,
  ParsePhoneNumber,
  StartBookingTimer,
  SetToken,
  OpenAppointmentsModal,
  timeFromMilitaryTime,
  timeFromDisplayTime,
  ampmFromDisplayTime,
  DataValue,
  CheckboxChecked
}
